// clientreact/src/components/AcronymForm.tsx
import React, { useState } from 'react';
import type {Acronym} from '../types/acronym';
import './styles/AcronymForm.css';

interface AcronymFormProps {
  onAddAcronym: (newAcronym: Omit<Acronym, 'id'>) => void;
}

const AcronymForm: React.FC<AcronymFormProps> = ({ onAddAcronym }) => {
  const [isFormVisible, setIsFormVisible] = useState(false);
  const [acronym, setAcronym] = useState('');
  const [definition, setDefinition] = useState('');
  const [description, setDescription] = useState('');
  const [formError, setFormError] = useState<string | null>(null);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    // Validation
    if (!acronym.trim() || !definition.trim()) {
      setFormError('Acronym and definition are required');
      return;
    }

    // Create new acronym object
    const newAcronym = {
      acronym: acronym.trim(),
      definition: definition.trim(),
      description: description.trim(),
    };

    // Add the acronym
    onAddAcronym(newAcronym);

    // Reset form
    setAcronym('');
    setDefinition('');
    setDescription('');
    setFormError(null);
    setIsFormVisible(false);
  };

  return (
    <div className="acronym-form-container">
      {isFormVisible ? (
        <>
          <h2>Add New Acronym</h2>
          <form onSubmit={handleSubmit} className="acronym-form">
            {formError && <div className="form-error">{formError}</div>}

            <div className="form-group">
              <label htmlFor="acronym">Acronym:</label>
              <input
                type="text"
                id="acronym"
                value={acronym}
                onChange={(e) => setAcronym(e.target.value)}
                placeholder="Enter acronym (e.g., API)"
              />
            </div>

            <div className="form-group">
              <label htmlFor="definition">Definition:</label>
              <input
                type="text"
                id="definition"
                value={definition}
                onChange={(e) => setDefinition(e.target.value)}
                placeholder="Enter definition (e.g., Application Programming Interface)"
              />
            </div>

            <div className="form-group">
              <label htmlFor="description">Description (optional):</label>
              <textarea
                id="description"
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="Enter a brief description"
              />
            </div>

            <div className="form-actions">
              <button type="submit" className="submit-button">Add Acronym</button>
              <button
                type="button"
                className="cancel-button"
                onClick={() => setIsFormVisible(false)}
              >
                Cancel
              </button>
            </div>
          </form>
        </>
      ) : (
        <button
          className="add-button"
          onClick={() => setIsFormVisible(true)}
        >
          Add New Acronym
        </button>
      )}
    </div>
  );
};

export default AcronymForm;

// clientng/src/app/components/acronym-form/acronym-form.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { Acronym } from '../../models/acronym.model';
import { MaterialModule } from '../../material.module';

@Component({
  selector: 'app-acronym-form',
  standalone: true,
  imports: [CommonModule, FormsModule, MaterialModule],
  templateUrl: './acronym-form.component.html',
  styleUrls: ['./acronym-form.component.css']
})
export class AcronymFormComponent {
  @Output() addAcronym = new EventEmitter<Omit<Acronym, 'id'>>();

  isFormVisible = false;
  acronym = '';
  definition = '';
  description = '';
  formError: string | null = null;

  toggleFormVisibility(): void {
    this.isFormVisible = !this.isFormVisible;
    if (!this.isFormVisible) {
      this.resetForm();
    }
  }

  onSubmit(): void {
    // Validation
    if (!this.acronym.trim() || !this.definition.trim()) {
      this.formError = 'Acronym and definition are required';
      return;
    }

    // Create new acronym object
    const newAcronym = {
      acronym: this.acronym.trim(),
      definition: this.definition.trim(),
      description: this.description.trim()
    };

    // Emit the new acronym
    this.addAcronym.emit(newAcronym);

    // Reset form
    this.resetForm();
    this.isFormVisible = false;
  }

  resetForm(): void {
    this.acronym = '';
    this.definition = '';
    this.description = '';
    this.formError = null;
  }
}

<mat-card class="form-card">
  <div *ngIf="isFormVisible">
    <mat-card-header>
      <mat-card-title>Add New Acronym</mat-card-title>
    </mat-card-header>
    <mat-card-content>
      <form (ngSubmit)="onSubmit()" class="acronym-form">
        <mat-error *ngIf="formError">{{ formError }}</mat-error>

        <mat-form-field appearance="outline" class="form-field">
          <mat-label>Acronym</mat-label>
          <input
            matInput
            [(ngModel)]="acronym"
            name="acronym"
            placeholder="Enter acronym (e.g., API)"
            required
          />
          <mat-icon matSuffix>short_text</mat-icon>
        </mat-form-field>

        <mat-form-field appearance="outline" class="form-field">
          <mat-label>Definition</mat-label>
          <input
            matInput
            [(ngModel)]="definition"
            name="definition"
            placeholder="Enter definition (e.g., Application Programming Interface)"
            required
          />
          <mat-icon matSuffix>text_fields</mat-icon>
        </mat-form-field>

        <mat-form-field appearance="outline" class="form-field">
          <mat-label>Description (optional)</mat-label>
          <textarea
            matInput
            [(ngModel)]="description"
            name="description"
            placeholder="Enter a brief description"
            rows="4"
          ></textarea>
          <mat-icon matSuffix>description</mat-icon>
        </mat-form-field>

        <div class="form-actions">
          <button mat-raised-button color="primary" type="submit">
            <mat-icon>add</mat-icon> Add Acronym
          </button>
          <button
            mat-button
            color="warn"
            type="button"
            (click)="toggleFormVisibility()"
          >
            <mat-icon>cancel</mat-icon> Cancel
          </button>
        </div>
      </form>
    </mat-card-content>
  </div>

  <button
    *ngIf="!isFormVisible"
    mat-raised-button
    color="accent"
    (click)="toggleFormVisibility()"
    class="add-button"
  >
    <mat-icon>add</mat-icon> Add New Acronym
  </button>
</mat-card>
