// clientng/src/app/components/acronym-search/acronym-search.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { MaterialModule } from '../../material.module';

@Component({
  selector: 'app-acronym-search',
  standalone: true,
  imports: [CommonModule, FormsModule, MaterialModule],
  templateUrl: './acronym-search.component.html',
  styleUrls: ['./acronym-search.component.css']
})
export class AcronymSearchComponent {
  @Output() search = new EventEmitter<{ query: string, type: 'acronym' | 'definition' }>();

  searchQuery: string = '';
  searchType: 'acronym' | 'definition' = 'acronym';

  onSubmit(): void {
    if (this.searchQuery.trim()) {
      this.search.emit({
        query: this.searchQuery,
        type: this.searchType
      });
    }
  }
}

<mat-card class="search-card">
  <mat-card-header>
    <mat-card-title>Search Acronyms</mat-card-title>
  </mat-card-header>
  <mat-card-content>
    <form (ngSubmit)="onSubmit()">
      <div class="search-controls">
        <mat-form-field appearance="outline" class="search-input">
          <mat-label>Search term</mat-label>
          <input
            matInput
            [(ngModel)]="searchQuery"
            name="searchQuery"
            placeholder="Enter search term..."
            minlength="1"
          />
          <mat-icon matSuffix>search</mat-icon>
        </mat-form-field>

        <mat-radio-group
          [(ngModel)]="searchType"
          name="searchType"
          class="search-type-selector"
        >
          <mat-radio-button value="acronym">Search by Acronym</mat-radio-button>
          <mat-radio-button value="definition">Search by Definition</mat-radio-button>
        </mat-radio-group>

        <button mat-raised-button color="primary" type="submit">
          <mat-icon>search</mat-icon>
          Search
        </button>
      </div>
    </form>
  </mat-card-content>
</mat-card>

// client/src/components/AcronymSearch.tsx
import React, { useState } from 'react';
import './styles/AcronymSearch.css';

interface AcronymSearchProps {
  onSearch: (query: string, type: 'acronym' | 'definition') => void;
}

const AcronymSearch: React.FC<AcronymSearchProps> = ({ onSearch }) => {
  const [searchQuery, setSearchQuery] = useState('');
  const [searchType, setSearchType] = useState<'acronym' | 'definition'>('acronym');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (searchQuery.trim()) {
      onSearch(searchQuery, searchType);
    }
  };

  return (
    <div className="search-container">
      <h2>Search Acronyms</h2>
      <form onSubmit={handleSubmit}>
        <div className="search-controls">
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Enter search term..."
            className="search-input"
            size={10}
            minLength={1}
          />

          <div className="search-type-selector">
            <label>
              <input
                type="radio"
                name="searchType"
                checked={searchType === 'acronym'}
                onChange={() => setSearchType('acronym')}
              />
              Search by Acronym
            </label>

            <label>
              <input
                type="radio"
                name="searchType"
                checked={searchType === 'definition'}
                onChange={() => setSearchType('definition')}
              />
              Search by Definition
            </label>
          </div>

          <button type="submit" className="search-button">Search</button>
        </div>
      </form>
    </div>
  );
};

export default AcronymSearch;
